language: node_js
services:
  - docker
stages:
  - name: Quality
  - name: Test
  - name: Build
  - name: Deploy
  - name: Smoke Test
  - name: Monitor
jobs:
  include:
    - stage: Quality
      env: step=Snyk vulnerability check
      name: Snyk vulnerability check
      script: snyk test
    - env: step=Detect secrets in files
      name: Detect secrets in files
      script:
        - npm run detect-secrets $(git ls-files)
    - env: step=Run commit lint
      name: Run commit lint
      script:
        - commitlint-travis
    - env: step=Run ESLint check
      name: Run ESLint check
      script:
        - npm run lint:verify
    - env: step=Run Prettier check
      name: Run Prettier check
      script:
        - npm run prettier:verify
    - stage: Test
      env: step=Run tests and Sonar Scanner
      name: Run tests and Sonar Scanner
      script:
        - touch .env
        - npm test
        - npx sonar-scanner
    - env: step=Run contract tests
      name: Run contract tests
      before_script:
        - npm start &
      script:
        - npm run build:postman
        - npm run test:api
    - env: step=Run Pact tests
      name: Run Pact tests
      script:
        - touch .env
        - npm run test:api:consumer
        - npm run publish:pact
        - export CI=true && npm run test:api:provider
    - stage: Build
      env: step=Build and Publish image
      name: Build and Publish image
      script:
        - ./scripts/buildAndPublish.sh
    - stage: Deploy
      env: step=Deploy the images
      name: Deploy the images
      script:
        - ./scripts/deploy.sh
    - stage: Smoke Test
      env: step=Run contract tests
      name: Run contract tests
      script:
        - npm run build:postman
        - npm run test:api -- --env-var "baseUrl=$APP_HOST"
    - stage: Monitor
      env: step=Run Snyk Monitor
      name: Run Snyk Monitor
      script: snyk monitor
